<?php
namespace Moon\Config;

class Code {
    const SUCCESS = 1000 ;  //成功
    const PARAMS_ERROR = 1001 ;  //参数错误
    const ACCOUNT_EXISTS = 1002 ;  //账号已存在
    const NOT_NEW_ACCOUNT = 1003 ;  //新账号才能注册
    const CREATE_YK_ACCOUNT_FAIL = 1004 ;  //创建游客账号失败
    const ACCOUNT_BIND_ALREADY = 1005 ;  //账号已经绑定平台
    const ACCOUNT_NOT_THE_SAME = 1006 ;  //平台绑定的游戏账号和玩家本地保存的不一致
    const CREATE_PLATFORM_ACCOUNT_FAIL = 1007 ;  //创建平台账号失败
    const YK_ONLY_ONE_DEVICE = 1008 ;  //游客账号只能在一个设备上使用
    const NOT_FIND_ACCOUNT = 1009 ;  //未找到账号信息
    const UPDATE_USER_FAIL = 1010 ;  //修改用户信息失败
    const NOT_FOUND_FRIEND = 1011 ;  //找不到好友
    const ALREADY_ADD_FRIEND = 1012 ;  //已经添加此好友
    const ADD_FRIEND_FAIL = 1013 ;  //添加好友失败
    const NO_FRIEND_INFO = 1014 ;  //没有好友信息
    const DEL_FRIEND_FAIL = 1015 ;  //删除好友失败
    const CANNOT_ADD_SELF = 1016 ;  //不能添加自己为好友
    const NO_MAIL_INFO = 1017 ;  //没有邮件信息
    const NOT_FOUND_MAIL = 1018 ;  //没找到对应ID的邮件
    const DATA_ERROR = 1019 ;  //数据错误
    const ALREADY_GET_REWARD = 1020 ;  //奖励已领取过
    const LIMIT_FRIEND = 1021 ;  //达到好友上限
    const LIMIT_RECV_VIT = 1022 ;  //达到接收体力上限
    const LIMIT_SEND_VIT = 1023 ;  //达到赠送体力上限
    const NO_FRIEND_VIT = 1024 ;  //没有可赠送体力的好友
    const ALREADY_READ_MAIL = 1025 ;  //邮件已处理
    const SIGN_FAIL = 1026 ;  //签到失败
    const LOGIN_FAIL = 1027 ;  //登录失败
    const CONDITION_FAIL = 1028 ;  //条件不满足
    const SESSION_OUT_DATE = 1029 ;  //会话过期
    const UNLOCK_FAIL = 1030 ;  //解锁失败
    const MAIL_OUT_DATE = 1031 ;  //邮件过期
    const ALREADY_SEND_VIT = 1032 ;  //已赠送过体力
    const LIMIT_FRIEND_OTHER = 1033 ;  //对方的好友已满
    const NO_NOTICE_INFO = 1034 ;  //没有系统公告信息
    const NOTICE_OUT_DATE = 1035 ;  //系统公告过期
    const NOTICE_GET_REWARD = 1036 ;  //系统公告物品已领取过
    const ALREADY_ADD_FRIEND_RREQ = 1037 ;  //好友申请已发出，请等待对方确认
    const FRIEND_LIMIT_RECV_VIT = 1038 ;  //对方达到接收体力上限
    const NOT_FIND_REDEEM = 1039 ;  //找不到兑换码
    const REDEEM_NOT_START = 1040 ;  //兑换码未开放
    const REDEEM_OUT_DATE = 1041 ;  //兑换码已过期
    const ALREADY_USE_REDEEM = 1042 ;  //兑换码已领取
    const LIMIT_USE_REDEEM = 1043 ;// 兑换码已领取本批次兑换码次数已达上限
    const NOT_CHANNEL_REDEEM = 1044 ;// 兑换码与作用体不匹配
    const NOT_VERSION_REDEEM = 1045 ;// 兑换码与作用的版本不匹配
    const ERR_INPUT_TEXT = 1046 ;// 字符输入不合法
    const MUST_UPDATE_CLIENT = 1047 ;// 请先更新客户端
    const COLLECT_HAVE_RECEIVE = 1048 ;// 收集已经领取
    const COLLECT_NOT_START = 1049 ;// 收集未开始
    const COLLECT_HAVE_END = 1050 ;// 收集已结束
    const COLLECT_NOT_REACH_CONDITION = 1051 ;// 收集未达到条件
    const REQUEST_REPEAT = 1052 ;// 请求重复了
    const NOT_FIRST_PAY = 1053 ;// 非首充
    const FIRST_PAY_AWARD_HAVE_RECEIVE = 1054 ;//首充奖励已领取
    const SIGN_CONDITION_FAIL = 1055; //用户签到条件不满足
    const ALREADY_SIGN = 1056; //用户已签到
    const SIGN_LIMIT = 1057; //签到限制
    const ALREADY_RECV_ADD_FRIEND_RREQ = 1058;//已经接受过添加好友请求
    const ACTION_NOT_FOUND = 1101 ;//action不存在
    const CONTROLLER_NOT_FOUND = 1102 ;//controller不存在
    const SERVER_OFF = 1107; // 服务关闭了
    const ALIPAY_AUTH_ERROR = 1108; //支付宝授权失败
    const REDIS_CONNECT_ERROR = 1109 ;//redis连接失败
    const REDIS_AUTH_ERROR = 1110 ;//redis验证失败
    const REDIS_SET_ERROR = 1111 ;//redis写入失败
    const SIGN_ERROR = 1112;//签名错误
    const MYSQL_SAVE_ERROR = 1113;//mysql保存失败
    const NO_UPDATE_BULLETIN = 1114;//没有更新公告
    const NO_RESCUE_SELF_INFO = 1115;//没有救援资格信息
    const CANNOT_CREATE_RESCUE = 1116;//没有创建救援次数
    const RESCUE_NOT_FINISH = 1117;//救援尚未完成或有参与者未领取奖励
    const NO_RESCUE_INFO = 1118;//无此救援信息
    const RESCUE_ALREADY_SUCCESS = 1119;//救援已经完成
    const RESCUE_NOT_START = 1120;//救援尚未开始
    const RESCUE_TIME_OUT = 1121;//救援已超时关闭
    const CANNOT_ASSIST_RESCUE = 1122;//没有协助救援次数
    const NO_SUCH_RESCUE_INVITATION = 1123;//该邀请信息不存在
    const ALREADY_INVITED = 1124;//已邀请该好友
    const RESCUE_NOT_CREATED = 1125;//尚未创建救援
    const RESCUE_CONSUME_ERROR = 1126;//客户端救援金额错误
    const INVITED_TODAY = 1127;//今日已经邀请过该好友
    const OVERLIMIT_PERSONS = 1128;//今天发送太多私信，请明天再来吧
    const AWARDED_USER = 1129;//已经领取过该好友的邀请奖励
    const CANNOT_AWARDED = 1130;//无法领取奖励
    const GOLD_NOT_ENOUGH = 1131;//金币不足
    const CAN_NOT_ADD_PERMISSION = 1132;//无法再获取次数
    const NO_PURCHASE_PERMISSION = 1133;//无法再购买次数
    const RESCUE_REWARD_ALREADY_GET = 1134;//已领取奖励
    const ORDER_PROCESSED = 1135;//订单已处理过
    const RESCUE_END = 1136;//救援活动已关闭
    const RESCUE_WEEK_REWARD_CLAIMED = 1137;//用户周救援奖励已领取
    const RESCUE_WEEK_REWARD_LACK_CONDITION = 1139;//用户不满足周救援奖励领取条件
    const LOTTERY_PERMISSION_LACK = 1140;//抽奖资格不足
    const IMEI_ERROR = 1141 ;  //设置IEMI错误
    const LOTTERY_END = 1142 ;  //大转盘结束
    const LOTTERY_ERROR = 1143 ;  //大转盘出错
    const RED_PACKET_CLOSED = 1144; //红包活动未开启
    const ATTENDANCE_END = 1145 ;  //连续签到活动结束
    const ATTENDANCE_ERROR = 1146 ;  //连续签到活动出错
    const ATTENDANCE_ALREADY = 1147 ;  //已签到
    const CREATE_RED_ERROR = 1148 ;  //创建红包活动失败
    const TREASURE_END = 1149 ;  //疯狂寻宝活动结束
    const TREASURE_ERROR = 1150 ;  //疯狂寻宝活动出错
    const NO_MATCH_RED_PACKET = 1151;  //没有获取到匹配金额的红包
    const TREASURE_GET_LIMIT = 1152 ;  //疯狂寻宝获取已达限制
    const TREASURE_SEND_LIMIT = 1153 ;  //疯狂寻宝赠送已达限制
    const TREASURE_LACK_CONDITION = 1154 ;  //疯狂寻宝兑换条件不满足
    const TREASURE_FRIEND_GET_LIMIT = 1155 ;  //疯狂寻宝好友获取已达限制
    const TREASURE_PIECE_NOT_ENOUGH = 1156 ;  //疯狂寻宝碎片不足
    const RED_PACKET_AWARD_ERROR = 1157;  //红包领取失败
    const NO_RED_PACKET = 1158;  //红包已领完
    const RECALLED_TODAY = 1159;//今日已向该好友发送过召回邀请
    const RECALLED_AWARDED = 1160;//已经领取过该名次的奖励
    const AWARDED_TOO_MUCH = 1161;//红包领取数量已超过上线
    const NO_ENOUGH_RECALL = 1162;//没有召回足够数量的好友
    const WEEKRACE_TIME_ERROR = 1163;//周赛水果忍者时间比对错误

}